### ISSUE TITLE
Unclear how to clone a github repository

### ISSUE THREAD

**Issue by crutkas** [Microsoft/windows-dev-box-setup-scripts#44]
Trying to clone one of our official repositories.  It feels like we should be able to do this.  Is the correct way to do this via powershell?

**Comment by crutkas** [comment]
Install git tools, refresh env then do the clone.

**Comment by gep13** [comment]
@crutkas as you have found out, the issue here is that after installation of some tools, the commands associated with those tools are not available in the current command/powershell window until you refresh.  This is normally due to the fact that a change to the system PATH variable has been made, which isn't available in the current command/powershell window.

There are two solutions to this.  Firstly, you can either close and re-open the current command/powershell window.  Or, Chocolatey provides the `refreshenv` command, which you can use to achieve the same thing, without needing to close the window.
